-- Run this SQL in your Supabase SQL Editor to create the necessary table

-- 1. Create the 'scores' table
create table public.scores (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  game_id text not null,
  username text not null,
  high_score bigint not null default 0
);

-- 2. Enable Row Level Security (RLS)
-- This is a security best practice in Supabase
alter table public.scores enable row level security;

-- 3. Create Access Policies
-- Allow anyone (even unauthenticated users) to read the leaderboard
create policy "Enable read access for all users"
on public.scores for select
to anon
using (true);

-- Allow anyone to submit a score
-- Note: logic in main.py handles the "is it a high score" check, but ideally 
-- we would verify this on the backend or use authentication.
create policy "Enable insert access for all users"
on public.scores for insert
to anon
with check (true);

-- 4. Optimization
-- Create an index to make fetching the top scores faster
create index scores_game_id_high_score_idx on public.scores (game_id, high_score desc);
